package com.decathlon.pointcalculator;

public enum GameType {
	FIELD_LONG_JUMP, FIELD_POLE_JUMP, FIELD_HIGH_JUMP, FIELD_SHOT_PUT, FIELD_DISCUS_THROW, FIELD_JAVELIN_THROW, TRACK_100M, TRACK_110M, TRACK_400M, TRACK_1500M;

}
